# Generated by Django 2.2.24 on 2021-08-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_cookbook_ingredient_member_preparation_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_yield',
            field=models.CharField(default='default_yield', max_length=200),
            preserve_default=False,
        ),
    ]
